name: dong_gan_dan_che
description:

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # 图标
  font_awesome_flutter: ^9.1.0

  # 网络通信
  dio: ^4.0.0
  # 网络缓存
  dio_http_cache: ^0.3.0
  # WebSocket通信
  web_socket_channel: ^2.1.0

  # 屏幕适配
  flutter_screenutil: ^5.0.0+2
  # 提供路径操作
  path_provider: ^2.0.2
  # 拉动更新
  pull_to_refresh: ^2.0.0

  # 声网SDK
  agora_rtc_engine: ^4.0.6
  permission_handler: ^6.0.1
  # 视频播放
  video_player: ^2.1.14
  # 图片拣选
  image_picker: ^0.8.2
  # 底部选择器
  flutter_picker: ^2.0.2 #https://pub.dev/packages/flutter_picker
  # 蓝牙
  flutter_blue: ^0.8.0
  # 面包屑弹出提示
  fluttertoast: ^8.0.8
  # 加载进度
  flutter_easyloading: ^3.0.0
  # 轮播图
  flutter_swiper: ^1.1.6
  # 缓存
  cached_network_image: ^3.1.0

  # 事件
  event_bus: ^2.0.0

  # 微信
  fluwx: ^3.5.0

  # 根据url地址启动, 可以启动 浏览器/邮箱/电话/短信等
  url_launcher: ^6.0.9

  # 基础的点击
  tapped: any
  # map取值
  safemap: any

  # 屏幕控制常亮
  wakelock: ^0.5.3+3

  # 布局
  rxdart: ^0.26.0

  # 格式化插件
  intl: ^0.17.0

  # mqtt
  mqtt_client: ^9.6.3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/login/logo.png
    - assets/images/common/default.jpg
    - assets/images/common/circle.png
    - assets/images/common/circle-checked.png
    - assets/images/common/camera.png
    - assets/images/common/exit.png
    - assets/images/common/close.webp
    - assets/images/common/share.png
    - assets/images/common/sceen.png
    - assets/images/common/gift.png
    - assets/images/common/dg.webp
    - assets/images/common/back.webp
    - assets/images/common/calendar.png
    - assets/images/common/wx.png
    - assets/images/common/ali.png

    - assets/images/common/cfk.webp
    - assets/images/common/cqe.webp
    - assets/images/common/cjf.webp
    - assets/images/common/broadcast.webp
    - assets/images/common/fun_home_pull_down.png
    - assets/images/common/member.png
    - assets/images/common/scan.webp
    - assets/images/common/chat.webp
    - assets/images/common/game.webp
    - assets/images/common/history.webp
    - assets/images/common/hot.png
    - assets/images/common/search.webp

    - assets/images/gift/b.png
    - assets/images/gift/1314.png
    - assets/images/gift/bangbangtang.png
    - assets/images/gift/aini.png
    - assets/images/gift/paoche.png
    - assets/images/gift/qiqiu.png
    - assets/images/gift/shouhu.png
    - assets/images/gift/xingxing.png
    - assets/images/gift/yingguangbang.png
    - assets/images/nav/admin.png
    - assets/images/nav/admin-sel.png
    - assets/images/nav/device.png
    - assets/images/nav/device-sel.png
    - assets/images/nav/index.png
    - assets/images/nav/index-sel.png
    - assets/images/nav/match.png
    - assets/images/nav/match-sel.png
    - assets/images/nav/video.png
    - assets/images/nav/video-sel.png
    - assets/images/num/0.webp
    - assets/images/num/1.webp
    - assets/images/num/2.webp
    - assets/images/num/3.webp
    - assets/images/num/4.webp
    - assets/images/num/5.webp
    - assets/images/num/6.webp
    - assets/images/num/7.webp
    - assets/images/num/8.webp
    - assets/images/num/9.webp

    - assets/images/drag/add.png
    - assets/images/drag/cal.png
    - assets/images/drag/gl.png
    - assets/images/drag/panel.png
    - assets/images/drag/sub.png
    - assets/images/drag/time.png
    - assets/images/drag/zl.png

    - assets/images/live/close/fire.png
    - assets/images/live/close/gift.png

    - assets/images/cate/tab-0.webp
    - assets/images/cate/tab-1.webp
    - assets/images/cate/tab-2.webp
    - assets/images/cate/tab-3.webp
    - assets/images/cate/tab-4.webp
    - assets/images/cate/tab-5.webp
    - assets/images/cate/tab-6.webp
    - assets/images/cate/tab-7.webp
    - assets/images/cate/tab-8.webp
    - assets/images/cate/tab-9.webp
    - assets/images/cate/tab-10.webp

    - assets/images/device/scaning.png
    - assets/images/device/wait.png

    - assets/images/admin/collection.png
    - assets/images/admin/interact.png
    - assets/images/admin/pay.png
    - assets/images/admin/setting.png
    - assets/images/admin/setting/info.png
    - assets/images/admin/setting/lock.png
    - assets/images/admin/setting/toCoach.png
    - assets/images/admin/setting/toStudent.png
    - assets/images/admin/setting/exit.png
    - assets/images/admin/setting/close.png
    - assets/images/admin/bg.png
    - assets/images/admin/recharge.png
    - assets/images/admin/recharge_record.png
    - assets/images/admin/border.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
